publish = "netlify"
plugins = []
functionsDirectory = "/workspaces/Steinway/netlify/function"
functionsDirectoryOrigin = "config"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/workspaces/Steinway/netlify"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Build complete'"
functions = "/workspaces/Steinway/netlify/function"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]